#import "../assets/tables/bmc-channels-table.typ": bmc-channels-table
#import "../assets/tables/bmc-pricing-table.typ": bmc-pricing-table
#import "../assets/tables/bmc-costs-table.typ": bmc-costs-table

= Analiza dziedziny i kontekst biznesowy


== Analiza dziedziny


=== Charakterystyka kancelarii adwokackich w kontekście aplikacji


=== Problemy w tradycyjnym obiegu dokumentów


=== Uzasadnienie wyboru podejścia mobilnego z kodami QR


== Aspekty biznesowe


Analizę biznesową aplikacji QRLawyer wykonano w oparciu o metodykę Business Model Canvas. Należy podkreślić, że przedstawiona analiza ma charakter wyłącznie teoretyczny i prospektywny. W ramach niniejszej pracy inżynierskiej zespół nie wdraża aplikacji komercyjnie ani nie realizuje opisanego modelu biznesowego. Celem rozdziału jest wskazanie potencjalnych możliwości i kierunków rozwoju komercyjnego projektu, gdyby zdecydowano o jego kontynuacji.


=== Segmenty Klientów

Aplikacja QRLawyer kierowana jest do dwóch odrębnych segmentów klientów, które różnią się skalą działalności, strukturą organizacyjną oraz sposobem podejmowania decyzji zakupowych. Oba segmenty mieszczą się w obrębie polskiego rynku prawniczego, a konkretnie wśród kancelarii adwokackich i radcowskich -- grup zawodowych o najbardziej zbliżonej charakterystyce pracy i potrzebach w zakresie zarządzania dokumentacją. Według danych dostępnych na dzień przygotowania niniejszej pracy, w krajowych rejestrach znajduje się 34 279 adwokatów#cite(<rejestr-adwokatow>) oraz 56 359 radców prawnych#cite(<rejestr-radcow>), co łącznie daje ponad 90 000 potencjalnych użytkowników indywidualnych. Liczba ta stanowi istotny wskaźnik potencjału rynkowego aplikacji, nawet przy założeniu stosunkowo niskiego współczynnika adopcji na wczesnym etapie.

Pierwszy segment obejmuje prawników prowadzących jednoosobową działalność gospodarczą w formie kancelarii adwokackiej lub radcowskiej. Są to osoby samodzielnie zarządzające całością dokumentacji, terminarzem i relacjami z klientami, często bez wsparcia administracyjnego. Dla tego segmentu kluczowym czynnikiem decyzyjnym jest niski próg wejścia, zarówno finansowy, jak i technologiczny. Decyzja o wyborze narzędzia podejmowana jest indywidualnie, bez konieczności konsultacji z innymi partnerami czy zarządem. W proponowanym modelu biznesowym segment ten jest adresowany poprzez bezpłatny, miesięczny okres próbny dostępny bezpośrednio po pobraniu aplikacji z App Store lub Google Play i założeniu konta. Celem jest obniżenie bariery wejścia i umożliwienie prawnikom samodzielnego zapoznania się z funkcjonalnościami aplikacji przed podjęciem decyzji o wykupieniu abonamentu.

Spełniane potrzeby tego segmentu obejmują przede wszystkim: centralizację dokumentacji i akt spraw w jednym miejscu dostępnym z urządzenia mobilnego, eliminację czasochłonnego przeszukiwania fizycznych akt dzięki kodom QR, automatyzację komunikacji z klientami poprzez powiadomienia mailowe o zmianie statusu sprawy oraz wygodne zarządzanie terminarzem zintegrowanym z kalendarzem systemowym telefonu. Dla prawnika działającego samodzielnie szczególnie istotna jest też funkcja rejestrowania czasu pracy, która ułatwia rozliczanie godzinowe z klientami.

Drugi segment obejmuje kancelarie zatrudniające więcej niż jednego prawnika -- od kilkuosobowych spółek partnerskich po średniej wielkości kancelarie z rozbudowaną strukturą pracowniczą. W tym segmencie aplikacja obsługuje wiele kont użytkowników w ramach jednej organizacji, z podziałem na superużytkownika (zazwyczaj wspólnik zarządzający lub szef kancelarii) oraz zwykłych użytkowników (prawnicy, aplikanci, pracownicy administracyjni). Decyzja zakupowa podejmowana jest na poziomie organizacji, a nie indywidualnego prawnika. Klientem i stroną umowy o świadczenie usług jest kancelaria jako podmiot. Dostęp do aplikacji w tym segmencie wymaga wykupienia abonamentu miesięcznego lub rocznego, z przewidywanym zróżnicowaniem oferty w ramach kilku poziomów cenowych (ang. _price tiers_), dostosowanych do liczby użytkowników i zakresu funkcjonalności.

Spełniane potrzeby tego segmentu wykraczają poza indywidualne zarządzanie sprawami i obejmują przede wszystkim: usprawnienie współpracy i przepływu informacji między pracownikami kancelarii na różnych szczeblach, scentralizowane zarządzanie bazą klientów i sprawami przez superużytkownika, kontrolę nad uprawnieniami i dostępem do danych poszczególnych pracowników, a także możliwość monitorowania aktywności i czasu pracy zespołu. Dla kancelarii wieloosobowej szczególną wartość stanowi możliwość natychmiastowego dostępu do informacji o dowolnej sprawie przez każdego uprawnionego pracownika, bez konieczności fizycznego odnajdywania akt lub pytania współpracowników.

Z perspektywy technicznej obydwa segmenty różnią się przede wszystkim sposobem korzystania z modułu zarządzania organizacją. W segmencie pierwszym konto organizacji tworzone jest przez jednego użytkownika, który pełni jednocześnie rolę superużytkownika i jedynego pracownika, a funkcje zarządzania zespołem pozostają nieaktywne lub nieistotne. W segmencie drugim organizacja posiada domyślnie jednego superużytkownika oraz dowolną liczbę zwykłych użytkowników, a system uprawnień i logów aktywności nabiera pełnego znaczenia operacyjnego. Rozróżnienie to ma bezpośrednie przełożenie na model abonamentowy: konto jednoosobowe może funkcjonować w ramach uproszczonego planu cenowego lub przedłużonego okresu próbnego, natomiast konta wieloosobowe wymagają wykupienia odpowiedniego poziomu subskrypcji uzależnionego od liczby aktywnych użytkowników w organizacji.

QRLawyer działa na rynku niszowym, adresując specyficzne potrzeby dwóch ściśle powiązanych grup zawodowych -- adwokatów i radców prawnych prowadzących kancelarie w Polsce. Wybór rynku niszowego jest świadomą decyzją projektową: zamiast tworzyć generyczne narzędzie do zarządzania dokumentami, aplikacja jest ściśle dopasowana do realiów pracy prawniczej, co stanowi jej główną przewagę konkurencyjną nad rozwiązaniami uniwersalnymi.

=== Relacje z klientami

Relacje z klientami w modelu biznesowym QRLawyer opierają się na następujących fundamentach: samoobsługowym modelu pozyskiwania i onboardingu użytkowników, zróżnicowanym wsparciu technicznym dostosowanym do poziomu subskrypcji oraz świadomym budowaniu lojalności i retencji opartym na uczciwym i przejrzystym podejściu do cennika. Charakter relacji różni się w zależności od segmentu klienta -- jednoosobowe kancelarie obsługiwane są niemal wyłącznie w modelu samoobsługowym, natomiast kancelarie wieloosobowe mogą liczyć na bardziej bezpośredni kontakt z zespołem.

Proces pozyskiwania klientów zaprojektowany jest jako w pełni samoobsługowy. Użytkownik pobiera aplikację z App Store lub Google Play, samodzielnie zakłada konto i tworzy organizację odpowiadającą jego kancelarii. Przy pierwszym uruchomieniu aplikacji wyświetlany jest interaktywny samouczek prowadzący użytkownika przez kluczowe funkcjonalności systemu: tworzenie spraw, zarządzanie dokumentami, generowanie i skanowanie kodów QR oraz konfigurację powiadomień. Samouczek można w dowolnym momencie wyłączyć lub reaktywować z poziomu ustawień aplikacji, co jest szczególnie przydatne przy wdrażaniu nowych pracowników w kancelariach wieloosobowych. Zespół rozważał także wdrożenie kontekstowych podpowiedzi (ang. _tooltips_) przy bardziej zaawansowanych funkcjach. Uzupełnieniem onboardingu w aplikacji byłaby strona internetowa produktu, zawierająca sekcję FAQ oraz bazę wiedzy dokumentującą wszystkie funkcjonalności systemu.

Model wsparcia technicznego jest zróżnicowany w zależności od wykupionego poziomu subskrypcji. Wszyscy użytkownicy mają dostęp do wsparcia mailowego oraz do zasobów samoobsługowych w postaci FAQ i bazy wiedzy na stronie internetowej. Wyższe poziomy cenowe przewidują rozszerzone formy wsparcia bezpośredniego, w tym dedykowaną obsługę klienta oraz możliwość indywidualnych ustaleń dotyczących wdrożenia dla kancelarii o szczególnych wymaganiach organizacyjnych lub technicznych. Takie podejście pozwala utrzymać niskie koszty obsługi klientów z segmentu jednoosobowego przy jednoczesnym zapewnieniu wysokiej jakości wsparcia dla bardziej wymagających klientów instytucjonalnych.

Zarządzanie subskrypcją, danymi organizacji oraz liczbą aktywnych użytkowników odbywałoby się za pośrednictwem dedykowanego panelu klienta dostępnego przez przeglądarkę internetową. Panel ten stanowiłby uzupełnienie aplikacji mobilnej o funkcje administracyjne wykraczające poza codzienne użytkowanie, takie jak zmiana planu abonamentowego, podgląd historii płatności czy zarządzanie kontami pracowników na poziomie organizacji. Szczegółowy model obsługi płatności pozostaje na etapie koncepcyjnym i wymagałby dalszego opracowania w ramach ewentualnej komercjalizacji projektu.

Strategia retencji klientów opiera się na założeniu uczciwego i przejrzystego modelu cenowego, w którym każdy poziom subskrypcji oferuje realną wartość adekwatną do ceny, bez stosowania mechanizmów wymuszających wybór wyższych poziomów. Planowane instrumenty budowania lojalności obejmują zniżki za wykupienie subskrypcji rocznej zamiast miesięcznej, okresowe promocje cenowe oraz powiadomienia przypominające o zbliżającym się końcu okresu próbnego, dające użytkownikowi czas na świadomą decyzję zakupową. Zgodnie z założeniami etycznymi projektu, QRLawyer świadomie rezygnuje z agresywnych technik marketingowych i tzw. _dark patterns_ na rzecz budowania długoterminowego zaufania użytkowników.

=== Kanały

Kanały dystrybucji i komunikacji QRLawyer obejmują zarówno platformy cyfrowe umożliwiające dotarcie do szerokiego grona potencjalnych użytkowników, jak i kanały branżowe pozwalające na bezpośrednie przeniknięcie do środowiska prawniczego. Na wczesnym etapie rozwoju produktu strategia kanałów opiera się przede wszystkim na niskich kosztach pozyskania klienta i możliwie szerokim zasięgu, z założeniem stopniowego rozszerzania działań wraz z ewentualnym wzrostem produktu.

Podstawowym kanałem dystrybucji aplikacji są sklepy App Store oraz Google Play, za pośrednictwem których użytkownicy mogą bezpłatnie pobrać aplikację na urządzenia mobilne z systemem iOS lub Android. Model dystrybucji przez sklepy aplikacji jest naturalnym wyborem dla produktu kierowanego do szerokiego grona indywidualnych profesjonalistów -- eliminuje bariery techniczne związane z instalacją oprogramowania, zapewnia wiarygodność produktu wynikającą z procesu weryfikacji przez platformę oraz umożliwia organiczne odkrycie aplikacji przez użytkowników przeszukujących sklep. W przypadku osiągnięcia przez produkt wstępnego sukcesu rynkowego lub pozyskania inwestorów, rozważana byłaby również bezpośrednia sprzedaż do większych kancelarii, potencjalnie z udziałem partnerów handlowych lub dedykowanego zespołu sprzedażowego.

Centralnym hubem komunikacyjnym i sprzedażowym byłaby dedykowana strona internetowa produktu, pełniąca jednocześnie kilka funkcji: strony docelowej, prezentującej propozycję wartości i cennik, bazy wiedzy i sekcji FAQ wspierającej onboarding i samoobsługę użytkowników, miejsca logowania do panelu klienta umożliwiającego zarządzanie subskrypcją i organizacją oraz -- w perspektywie długoterminowej -- punktu dostępu do webowej wersji aplikacji, gdyby taka powstała. Koncentracja wszystkich tych funkcji w jednym miejscu upraszcza ścieżkę użytkownika i buduje spójne doświadczenie marki.

W ramach działań marketingowych online rozważane byłyby kanały takie jak pozycjonowanie w wyszukiwarkach (SEO) ukierunkowane na frazy związane z zarządzaniem kancelarią i obiegiem dokumentów, płatne kampanie reklamowe w Google Ads oraz obecność w mediach społecznościowych, ze szczególnym uwzględnieniem LinkedIn jako platformy profesjonalnej, na której aktywni są prawnicy i osoby zarządzające kancelariami. Działania te miałyby na celu budowanie świadomości marki i generowanie ruchu na stronie internetowej produktu.

Istotnym elementem strategii dystrybucji byłoby dotarcie do środowiska prawniczego poprzez kanały branżowe, które cieszą się wysokim poziomem zaufania wśród adwokatów i radców prawnych. Obejmowałoby to nawiązanie współpracy z okręgowymi izbami adwokackimi i radcowskimi, obecność na konferencjach i wydarzeniach branżowych poświęconych prawu i technologiom prawniczym, a także publikacje i artykuły sponsorowane w branżowych mediach prawniczych. Kanały te są szczególnie wartościowe w kontekście rynku niszowego, gdzie rekomendacje i zaufanie środowiskowe odgrywają kluczową rolę w procesie decyzyjnym.

Uzupełnieniem powyższych kanałów byłby program poleceń, w ramach którego aktywni użytkownicy aplikacji otrzymywaliby korzyści, na przykład w postaci zniżki na kolejny okres subskrypcji lub przedłużenia okresu próbnego, za polecenie QRLawyer innemu prawnikowi lub kancelarii, która następnie założy konto. Program poleceń jest szczególnie efektywny w środowiskach zawodowych o silnych powiązaniach sieciowych, takich jak środowisko prawnicze, gdzie rekomendacja zaufanego członka sieci zawodowej ma znacznie większą siłę przekonywania od tradycyjnej reklamy.

Zgodnie z typologią kanałów stosowaną w metodyce Business Model Canvas, kanały QRLawyer można usystematyzować według dwóch kryteriów: własności kanału oraz stopnia bezpośredniości kontaktu z klientem. Poniższa tabela przedstawia tę klasyfikację:

//TODO: poprawić odstępy między akapitami, a elementami typu tabelki

#bmc-channels-table

Kanały własne bezpośrednie zapewniają pełną kontrolę nad doświadczeniem użytkownika i wyższą marżę, jednak wiążą się z wyższymi kosztami utrzymania. Kanały partnerskie, choć generują niższą marżę z uwagi na konieczność podziału korzyści z partnerem, umożliwiają znaczące poszerzenie zasięgu i budowanie wiarygodności w środowisku prawniczym, co w przypadku niszowego produktu skierowanego do konserwatywnej grupy zawodowej ma szczególne znaczenie strategiczne.

=== Propozycja wartości

Propozycja wartości QRLawyer opiera się na czterech filarach: nowości, wykonaniu zadania, redukcji kosztów oraz wygodzie i użyteczności. Każdy z tych elementów odpowiada na konkretną potrzebę lub bolączkę zidentyfikowaną w codziennej pracy kancelarii adwokackich i radcowskich. Celem aplikacji nie jest w krótkiej perspektywie zastąpienie istniejących, rozbudowanych systemów zarządzania kancelarią, lecz dostarczenie lekkiego, mobilnego i intuicyjnego narzędzia, które realnie usprawnia codzienne operacje prawnicze bez wysokiego progu wejścia technologicznego ani finansowego.

Kluczowym i najbardziej innowacyjnym elementem QRLawyer na tle istniejących rozwiązań dostępnych na polskim rynku prawniczym jest wykorzystanie kodów QR do integracji fizycznego archiwum dokumentów z cyfrowym systemem zarządzania sprawami. Żadne z obecnie dostępnych narzędzi dedykowanych kancelariom adwokackim i radcowskim nie oferuje analogicznego mechanizmu. Idea jest prosta, lecz przełomowa w kontekście realiów pracy prawniczej: kod QR generowany przez aplikację i drukowany bezpośrednio na naklejce jest przyklejany na fizyczną teczkę ze sprawą. Od tej chwili każdy uprawniony pracownik kancelarii może w ciągu kilku sekund uzyskać pełny dostęp do cyfrowych informacji o sprawie, bez konieczności przeglądania dziesiątek stron akt, pytania współpracowników czy przeszukiwania systemu. Fizyczny dokument i jego cyfrowy odpowiednik stają się nierozerwalnie połączone. Elementem nowości jest również mechanizm automatycznych powiadomień mailowych wysyłanych do klientów przy każdej zmianie statusu sprawy -- funkcjonalność, która automatyzuje komunikację będącą dotychczas w pełni manualnym i czasochłonnym obowiązkiem pracownika kancelarii.

QRLawyer został zaprojektowany z myślą o konkretnym celu: umożliwieniu prawnikom skupienia się na pracy merytorycznej poprzez eliminację zbędnych czynności administracyjnych. Aplikacja realizuje kompletny zestaw zadań operacyjnych kancelarii w jednym miejscu -- od zarządzania bazą klientów i sprawami, przez archiwizację dokumentów w formie PDF, po rejestrację czasu pracy i zarządzanie terminarzem. Propozycja wartości oparta na wykonaniu zadania jest szczególnie istotna dla jednoosobowych kancelarii, gdzie jeden prawnik musi samodzielnie obsługiwać zarówno warstwę merytoryczną, jak i administracyjną swojej działalności. Dla kancelarii wieloosobowych wartość ta przejawia się dodatkowo w usprawnieniu przepływu informacji między pracownikami. Każdy członek zespołu ma natychmiastowy dostęp do aktualnego stanu każdej sprawy, co eliminuje potrzebę wewnętrznej komunikacji w sprawach czysto statusowych.

Choć redukcja kosztów w przypadku QRLawyer nie przejawia się bezpośrednio w obniżeniu wydatków finansowych, jej głównym wymiarem jest redukcja kosztu czasu, zasobu szczególnie cennego w zawodach prawniczych, gdzie czas pracy jest bezpośrednio przeliczany na wynagrodzenie. Szacuje się, że prawnicy mogą tracić ok. 60% swojego czasu pracy na czynności czysto administracyjne: wyszukiwanie akt, ręczne informowanie klientów o statusie sprawy, koordynację terminów czy rejestrację czasu pracy#cite(<non-billable-report>). Automatyzacja tych procesów przez QRLawyer przekłada się na realne odzyskanie czasu, który może zostać przeznaczony na pracę merytoryczną generującą przychód. Dodatkowym wymiarem redukcji kosztów jest konsolidacja narzędzi -- aplikacja zastępuje jednocześnie kilka osobnych rozwiązań (kalendarz, system archiwizacji, komunikację z klientem, rejestrację czasu pracy), eliminując potrzebę utrzymywania wielu subskrypcji lub korzystania z nieefektywnych rozwiązań analogowych.

Wygoda użytkowania jest jedną z najsilniejszych propozycji wartości QRLawyer, wynikającą bezpośrednio z mobilnego charakteru aplikacji. Prawnik ma pełny dostęp do wszystkich spraw, dokumentów i informacji o klientach z poziomu smartfona, niezależnie od tego czy przebywa w kancelarii, w sądzie, u klienta czy w drodze. Szczególną wartość praktyczną stanowią trzy funkcjonalności: natychmiastowy dostęp do danych sprawy poprzez skanowanie kodu QR aparatem telefonu, automatyczne powiadomienia push o nadchodzących terminach zintegrowane z kalendarzem systemowym urządzenia oraz automatyczna komunikacja z klientem eliminująca konieczność ręcznego wysyłania wiadomości przy każdej zmianie statusu sprawy. Aplikacja została zaprojektowana z myślą o minimalnej krzywej uczenia się -- intuicyjny interfejs oparty na funkcjonalnym prototypie oraz interaktywny samouczek przy pierwszym uruchomieniu sprawiają, że użytkownik może rozpocząć efektywną pracę z systemem niemal natychmiast po instalacji.

=== Kluczowe zadania

Kluczowe zadania w modelu biznesowym QRLawyer obejmują wszystkie działania, które zespół musiałby realizować w sposób ciągły, aby produkt funkcjonował, rozwijał się i generował przychody. W przypadku produktu SaaS o charakterze niszowym, skierowanego do środowiska zawodowego o wysokich wymaganiach w zakresie bezpieczeństwa i niezawodności, kluczowe zadania koncentrują się wokół czterech obszarów: ciągłego rozwoju produktu, utrzymania i skalowania infrastruktury technicznej, obsługi klienta oraz zapewnienia bezpieczeństwa i zgodności z przepisami.

Najważniejszym i najbardziej strategicznym zadaniem byłby nieprzerwany rozwój aplikacji. Rynek technologii prawniczych charakteryzuje się dynamicznym tempem zmian -- stagnacja produktu w takim środowisku jest równoznaczna z utratą konkurencyjności. Strategia rozwoju zakładałaby wejście na rynek z kompletnym zestawem podstawowych funkcjonalności, a następnie systematyczne wprowadzanie usprawnień i nowych funkcjonalności w oparciu o informacje zwrotne od użytkowników oraz obserwację trendów rynkowych. Proces rozwoju produktu obejmowałby projektowanie i implementację nowych funkcji, testowanie jakości oprogramowania, wydawanie aktualizacji dla obu platform mobilnych (iOS i Android) oraz iteracyjne doskonalenie interfejsu użytkownika.

Utrzymanie niezawodnej infrastruktury technicznej stanowi fundament działania produktu SaaS. W początkowej fazie działalności rekomendowanym podejściem byłoby uruchomienie usługi na własnych serwerach wirtualnych u dostawców takich jak Hetzner lub OVH -- rozwiązanie to zapewnia pełną kontrolę nad środowiskiem przy stosunkowo niskich kosztach operacyjnych, odpowiednich dla wczesnego etapu produktu. Wraz ze wzrostem bazy użytkowników i wolumenu przetwarzanych danych naturalną ścieżką skalowania byłoby stopniowe przejście na infrastrukturę chmurową lub hybrydową z zarządzaną instancją bazy danych PostgreSQL. Takie podejście pozwala elastycznie dostosowywać zasoby do aktualnego obciążenia systemu bez konieczności ponoszenia wysokich kosztów infrastrukturalnych od pierwszego dnia działalności. Do stałych zadań operacyjnych w tym obszarze należałyby: monitorowanie dostępności i wydajności systemu, zarządzanie kopiami zapasowymi danych, wdrażanie aktualizacji infrastruktury oraz reagowanie na incydenty techniczne.

Wsparcie użytkowników byłoby realizowane wewnętrznie przez zespół produktowy, bez outsourcingu do zewnętrznych podmiotów. Decyzja o utrzymaniu obsługi klienta in-house wynika z przekonania, że bezpośredni kontakt z użytkownikami dostarcza cennych informacji zwrotnych napędzających rozwój produktu, a jakość wsparcia technicznego w niszowym produkcie skierowanym do profesjonalistów ma bezpośredni wpływ na retencję i reputację marki. Do zadań w tym obszarze należałyby: obsługa zgłoszeń mailowych, utrzymanie i aktualizacja bazy wiedzy oraz FAQ na stronie internetowej, a w przypadku wyższych tierów subskrypcji -- bezpośrednia obsługa klientów instytucjonalnych i koordynacja indywidualnych wdrożeń.

Zapewnienie bezpieczeństwa danych i zgodności z obowiązującymi przepisami prawa jest traktowane jako zadanie ciągłe, a nie jednorazowe działanie wdrożeniowe. Zmienne środowisko regulacyjne, a w szczególności w zakresie ochrony danych osobowych (RODO) oraz przepisów dotyczących świadczenia usług drogą elektroniczną, wymusza stały monitoring zmian prawnych i ich implementację w systemie. Do regularnych zadań w tym obszarze należałyby: przeprowadzanie audytów bezpieczeństwa aplikacji i infrastruktury, aktualizacja polityki prywatności i regulaminu usługi, monitorowanie i analiza logów systemowych pod kątem nieautoryzowanych działań oraz reagowanie na potencjalne incydenty bezpieczeństwa. Biorąc pod uwagę, że aplikacja przetwarza wrażliwe dane dotyczące spraw prawnych i danych osobowych klientów kancelarii, bezpieczeństwo informacji jest traktowane jako absolutny priorytet operacyjny.

W przypadku osiągnięcia przez produkt sukcesu rynkowego, rozważane byłoby rozszerzenie działalności poza pierwotnie zdefiniowany segment docelowy. Możliwe kierunki obejmują adaptację aplikacji dla innych typów kancelarii lub branż o zbliżonej charakterystyce obiegu dokumentów, a także rozwój pokrewnych produktów adresujących inne potrzeby rynku. Tego rodzaju ekspansja stanowiłaby naturalną konsekwencję zdobytego doświadczenia produktowego i bazy użytkowników, jednak wykracza poza zakres planów objętych niniejszą pracą inżynierską.

=== Kluczowe zasoby

Kluczowe zasoby QRLawyer obejmują wszystkie składniki niezbędne do tego, aby produkt mógł funkcjonować, dostarczać zdefiniowaną propozycję wartości i generować przychody. Zasoby te można podzielić na cztery kategorie: materialne, intelektualne, ludzkie i finansowe.

Do zasobów materialnych QRLawyer należą przede wszystkim infrastruktura serwerowa oraz urządzenia deweloperskie i testowe. Na etapie rozwoju produktu zespół korzysta z własnych urządzeń mobilnych (smartfonów z systemem iOS i Android) oraz emulatorów programowych do testowania aplikacji na obu platformach. Istotnym elementem ekosystemu produktu są drukarki termiczne do naklejek, służące do drukowania kodów QR bezpośrednio z aplikacji -- urządzenia te, choć nie są dostarczane przez twórców aplikacji, stanowią niezbędny element sprzętowy po stronie użytkownika końcowego i muszą być uwzględnione w dokumentacji wdrożeniowej oraz materiałach onboardingowych. W zakresie infrastruktury serwerowej, jak opisano w podrozdziale dotyczącym kluczowych zadań, rekomendowaną ścieżką byłoby rozpoczęcie od serwerów VPS i stopniowe przejście na infrastrukturę chmurową wraz ze wzrostem bazy użytkowników.

Najcenniejszym zasobem intelektualnym QRLawyer jest kod źródłowy aplikacji wraz z całą towarzyszącą dokumentacją techniczną i projektową, w tym funkcjonalny prototyp interfejsu użytkownika. W przypadku komercjalizacji produktu konieczne byłoby podjęcie dodatkowych kroków prawnych, w szczególności rejestracji znaku towarowego nazwy i logotypu QRLawyer oraz uregulowania kwestii własności intelektualnej między członkami zespołu w formie stosownych umów. Do zasobów intelektualnych zalicza się również wiedza dziedzinowa zespołu w zakresie specyfiki pracy kancelarii adwokackich i radcowskich, zgromadzona w toku konsultacji z przedstawicielami środowiska prawniczego, a także wiedza techniczna dotycząca implementacji systemu zarządzania dokumentami opartego na kodach QR.

Na etapie realizacji niniejszej pracy inżynierskiej zespół projektowy liczy pięć osób, z których każda wnosi kompetencje zarówno w obszarze technicznym (projektowanie, implementacja frontendu i backendu, testowanie), jak i dokumentacyjnym. W przypadku komercjalizacji produktu skład i struktura zespołu wymagałyby istotnej rekonfiguracji, ponieważ część obecnych członków zespołu nie jest zainteresowana aktywnym uczestnictwem w dalszym rozwoju produktu w charakterze zawodowym. Ewentualna firma rozwijająca QRLawyer musiałaby zatem pozyskać nowych pracowników lub współpracowników, obejmujących kompetencje kluczowe dla produktu SaaS: programistów mobilnych i backendowych, specjalistę ds. bezpieczeństwa i infrastruktury, osobę odpowiedzialną za obsługę klienta i wsparcie techniczne oraz specjalistę ds. marketingu i sprzedaży, ze szczególnym uwzględnieniem znajomości rynku legal tech. Zasoby ludzkie są w przypadku produktu technologicznego o charakterze niszowym zasobem krytycznym -- jakość i zaangażowanie zespołu bezpośrednio determinuje tempo rozwoju produktu i jakość obsługi klienta.

Finansowanie ewentualnej komercjalizacji QRLawyer pozostaje kwestią otwartą. Własne środki finansowe członków zespołu są ograniczone i niewystarczające do samodzielnego sfinansowania pełnego wdrożenia produktu, jego promocji oraz utrzymania infrastruktury w dłuższym horyzoncie czasowym. W związku z tym komercjalizacja produktu wymagałaby pozyskania zewnętrznych źródeł finansowania. Potencjalne ścieżki obejmują pozyskanie inwestora prywatnego lub funduszu inwestycyjnego zainteresowanego segmentem legal tech, aplikowanie o granty na innowacje technologiczne oferowane przez instytucje takie jak Narodowe Centrum Badań i Rozwoju lub fundusze unijne wspierające rozwój produktów cyfrowych, a także finansowanie przez akceleratory startupów technologicznych. Wybór optymalnej ścieżki finansowania byłby uzależniony od skali planowanej działalności, tempa wzrostu oraz gotowości zespołu do podjęcia zobowiązań wobec inwestorów zewnętrznych -- kwestie te wykraczają jednak poza zakres niniejszej pracy i wymagałyby odrębnej, szczegółowej analizy na etapie ewentualnej komercjalizacji.

=== Kluczowi partnerzy

Kluczowi partnerzy QRLawyer obejmują podmioty zewnętrzne, których zasoby, usługi lub zasięg są niezbędne do prawidłowego funkcjonowania produktu, realizacji propozycji wartości i dotarcia do segmentów klientów. W przypadku produktu SaaS o charakterze mobilnym sieć partnerów składa się przede wszystkim z dostawców infrastruktury technicznej, platform dystrybucji, dostawców usług komunikacyjnych oraz partnerów branżowych i finansowych.

Apple App Store oraz Google Play Store są podstawowymi i niezbędnymi partnerami dystrybucyjnymi QRLawyer. Obie platformy pełnią rolę jedynego kanału dystrybucji aplikacji mobilnej i warunkują dostęp do użytkowników końcowych na urządzeniach z systemem iOS i Android. Aplikacja QRLawyer byłaby dostępna w obu sklepach bezpłatnie -- subskrypcja byłaby dostępna wyłącznie za pośrednictwem strony internetowej produktu, z pominięciem systemów płatności wbudowanych w platformy. Strategia ta jest świadomą decyzją biznesową pozwalającą uniknąć prowizji pobieranych przez platformy od transakcji realizowanych przez ich systemy płatności.

Kluczowym partnerem technicznym byłby dostawca infrastruktury serwerowej -- w początkowej fazie działalności w formie serwera VPS, a docelowo dostawca usług chmurowych. Partnerstwo z dostawcą infrastruktury ma charakter krytyczny, ponieważ niezawodność i dostępność serwerów bezpośrednio determinuje jakość usługi świadczonej użytkownikom końcowym. Do dostawców infrastruktury technicznej zalicza się również operator usługi wysyłki poczty elektronicznej, odpowiedzialny za dostarczanie automatycznych powiadomień mailowych do klientów kancelarii przy zmianie statusu sprawy. Wybór konkretnego dostawcy w tym obszarze wymagałby analizy kosztów, niezawodności dostarczania wiadomości oraz zgodności z wymogami RODO.

Specyficznym i wyróżniającym elementem ekosystemu QRLawyer jest integracja z drukarkami termicznymi do naklejek, służącymi do drukowania kodów QR bezpośrednio z aplikacji. Moduł drukowania aplikacji został zaprojektowany z wykorzystaniem protokołów komunikacyjnych zapewniających kompatybilność z możliwie szeroką gamą urządzeń -- w tym z tańszymi drukarkami dostępnymi na rynku -- bez konieczności instalowania dedykowanego oprogramowania producenta. Takie podejście eliminuje zależność od konkretnego producenta i daje użytkownikom swobodę wyboru urządzenia odpowiadającego ich budżetowi i potrzebom. W perspektywie długoterminowej, w przypadku osiągnięcia przez produkt odpowiedniej skali, możliwe byłoby nawiązanie formalnych partnerstw z wybranymi producentami drukarek w celu certyfikacji kompatybilności i wspólnych działań marketingowych.

Kluczową rolę w strategii wejścia na rynek odgrywają partnerzy branżowi ze środowiska prawniczego, a w szczególności okręgowe izby adwokackie i radcowskie. Partnerstwo z izbami miałoby charakter promocyjno-dystrybucyjny: izby, jako instytucje cieszące się wysokim zaufaniem swoich członków, mogłyby rekomendować QRLawyer jako narzędzie wspierające cyfryzację kancelarii, organizować prezentacje produktu podczas wydarzeń branżowych lub udostępniać informacje o aplikacji w swoich kanałach komunikacji wewnętrznej. Relacja ta miałaby charakter partnerstwa obustronnie korzystnego -- izby zyskują narzędzie wspierające modernizację środowiska zawodowego, a QRLawyer uzyskuje wiarygodność i dostęp do precyzyjnie zdefiniowanej grupy docelowej.

Niezbędnym partnerem finansowym byłby operator systemu płatności obsługujący transakcje subskrypcyjne realizowane przez stronę internetową produktu. W tym obszarze rozważane byłyby rozwiązania takie jak Stripe, szczególnie atrakcyjne ze względu na rozbudowane wsparcie dla modeli subskrypcyjnych SaaS, łatwość integracji oraz aktywne wsparcie dla deweloperów chcących wdrożyć płatności poza ekosystemem App Store. Należałoby uwzględnić także lokalne polskie rozwiązania, jak Przelewy24 lub PayU, które mogą być preferowane przez część klientów z uwagi na znajomość marki i obsługę lokalnych metod płatności. Wybór operatora płatności wymagałby szczegółowej analizy kosztów transakcyjnych, dostępnych metod płatności oraz zgodności z wymogami regulacyjnymi dotyczącymi przechowywania danych finansowych.

=== Strumienie przychodów

Podstawowym i docelowo jedynym strumieniem przychodów QRLawyer byłyby opłaty subskrypcyjne pobierane cyklicznie (miesięcznie lub rocznie) za dostęp do aplikacji. Model subskrypcyjny jest naturalnym wyborem dla produktu SaaS skierowanego do profesjonalistów, zapewniając przewidywalność przychodów i umożliwiając planowanie kosztów infrastruktury oraz rozwoju produktu. Wszystkie transakcje realizowane byłyby wyłącznie za pośrednictwem strony internetowej produktu, z pominięciem systemów płatności wbudowanych w platformy App Store i Google Play -- decyzja ta pozwala zachować pełną marżę ze sprzedaży.

Struktura cenowa QRLawyer opierałaby się na kilku poziomach subskrypcji, zróżnicowanych pod względem dostępnych funkcjonalności, liczby użytkowników w ramach organizacji oraz zakresu wsparcia technicznego. Precyzyjne zdefiniowanie poziomów, ich zawartości i cen wymagałoby konsultacji ze specjalistą ds. strategii cenowej oraz analizy gotowości rynku do zapłaty -- kwestie te wykraczają poza zakres niniejszej pracy. Niemniej, jako punkt odniesienia dla przyszłych decyzji cenowych, warto przywołać dane z polskiego rynku systemów zarządzania kancelarią. LegalDesk, produkt Wolters Kluwer będący jednym z bardziej rozpoznawalnych rozwiązań na polskim rynku, oferuje trzy poziomy cenowe: Start (85 zł netto/miesiąc), Grow (170 zł netto/miesiąc) oraz Expand (242 zł netto/miesiąc)#cite(<legal-desk-pricing>). Są to jednak rozwiązania webowe o znacznie szerszym zakresie funkcjonalności, kierowane do kancelarii gotowych ponosić wyższe koszty. QRLawyer, jako aplikacja mobilna o węższym i bardziej wyspecjalizowanym zakresie, pozycjonowałby się cenowo poniżej tych wartości -- szczególnie w obrębie poziomu podstawowego, adresowanego do jednoosobowych kancelarii.

Orientacyjna struktura tierów mogłaby przyjąć następującą formę:

#bmc-pricing-table

Powyższe wartości mają charakter wyłącznie orientacyjny i poglądowy -- ich ostateczne ustalenie wymagałoby przeprowadzenia badań rynkowych oraz analizy konkurencji.

Kwestia modelu _freemium_, a ograniczonego czasowo okresu próbnego, wymaga odrębnej analizy. Z perspektywy założeń biznesowych zespołu, preferowanym kierunkiem jest model, w którym każdy aktywny użytkownik docelowo ponosi opłatę subskrypcyjną -- nawet jeśli jest to kwota minimalna na poziomie podstawowym. Podejście to eliminuje ryzyko charakterystyczne dla modelu _freemium_, w którym znaczna część użytkowników (często 80 – 90%) korzysta z produktu bezpłatnie, generując koszty infrastruktury bez odpowiadającego przychodu. Rekomendowanym rozwiązaniem byłoby zatem wprowadzenie ograniczonego czasowo okresu próbnego (np. 30 dni) z dostępem do pełnych funkcjonalności wybranego tiera, po którym użytkownik zobowiązany jest do wyboru płatnego planu lub rezygnacji z usługi. Takie podejście pozwala użytkownikowi ocenić wartość produktu przed podjęciem decyzji zakupowej, jednocześnie nie tworząc trwałej bazy nieaktywnych ekonomicznie użytkowników.

Standardowym i rekomendowanym instrumentem zwiększania retencji w modelach SaaS jest oferowanie zniżki za wykupienie subskrypcji rocznej zamiast miesięcznej. Badanie Recurly przeprowadzone na próbie ponad 1000 firm SaaS wykazało, że najpopularniejszą zniżką roczną jest równowartość dwóch miesięcy abonamentu gratis, co odpowiada oszczędności ~16,7% w stosunku do sumy opłat miesięcznych#cite(<recurly-discount-study>).
Dla użytkownika oznacza to niższy łączny koszt roczny, a dla dostawcy wyższy wskaźnik retencji i bardziej przewidywalny przepływ gotówki. Praktycy branży SaaS rekomendują przy tym komunikowanie tej zniżki jako konkretnej korzyści ("2 miesiące gratis") zamiast wartości procentowej, co jest odbierane przez użytkowników jako bardziej atrakcyjne i przejrzyste#cite(<medium-discount-article>). 

W perspektywie długoterminowej, po osiągnięciu przez produkt odpowiedniej dojrzałości i skali, rozważane mogłyby być uzupełniające strumienie przychodów. Obejmowałyby one jednorazowe opłaty za wdrożenie i konfigurację systemu dla większych kancelarii, płatne pakiety wsparcia technicznego wykraczające poza standardowy zakres obsługi klienta, a także potencjalne przychody z adaptacji produktu dla innych branż lub segmentów rynku, jak wspomniano w podrozdziale dotyczącym kluczowych zadań. Strumienie te mają jednak charakter uzupełniający i nie stanowią elementu modelu przychodowego na etapie wejścia na rynek.

=== Struktura kosztów

Struktura kosztów QRLawyer obejmuje wszystkie wydatki niezbędne do wytworzenia, utrzymania i rozwoju produktu oraz do prowadzenia działalności operacyjnej. Model biznesowy QRLawyer wpisuje się w kategorię struktury skoncentrowanej na wartości -- priorytetem jest jakość produktu, bezpieczeństwo danych i poziom obsługi klienta, a nie minimalizacja kosztów za wszelką cenę. Jednocześnie, jako produkt SaaS o stosunkowo niskich kosztach zmiennych w stosunku do przychodów, QRLawyer dysponuje potencjałem do osiągnięcia wysokiej marży brutto charakterystycznej dla tego modelu biznesowego. Koszty można podzielić na dwie kategorie: koszty stałe, ponoszone niezależnie od liczby aktywnych użytkowników, oraz koszty zmienne, rosnące proporcjonalnie do skali działalności.

Do kategorii kosztów stałych należą przede wszystkim:

- Wynagrodzenia zespołu -- w przypadku komercjalizacji produktu największą pozycją kosztową byłyby wynagrodzenia pracowników odpowiedzialnych za rozwój aplikacji, utrzymanie infrastruktury oraz obsługę klienta. Jest to dominujący koszt stały w większości firm SaaS na wczesnym etapie rozwoju.
- Infrastruktura serwerowa -- w początkowej fazie koszty serwera VPS są stosunkowo niskie i przewidywalne. Serwer VPS zapewnia dużą swobodę zarządzania i możliwość rozwoju infrastruktury przy zachowaniu rozsądnych kosztów, co czyni go jednym z najczęściej wybieranych rozwiązań dla projektów internetowych na etapie wzrostu. 
- Opłaty deweloperskie platform -- Apple pobiera roczną opłatę w wysokości 99 USD za konto deweloperskie w App Store, Google Play wymaga jednorazowej opłaty rejestracyjnej w wysokości 25 USD.
- Usługi zewnętrzne -- obejmują koszty operatora płatności, usługi wysyłki poczty elektronicznej oraz ewentualne licencje na oprogramowanie deweloperskie i narzędzia do monitorowania systemu.
- Koszty prawne i compliance — obejmują koszty ochrony własności intelektualnej, obsługi prawnej umów, bieżącej ogólnej obsługi prawnej oraz monitorowania zgodności z RODO i innymi regulacjami krajowymi oraz unijnymi.
- Marketing i pozyskiwanie klientów -- koszty utrzymania strony internetowej, działań SEO oraz ewentualnych kampanii reklamowych.

Do kategorii kosztów zmiennych należą między innymi:

- Koszty infrastruktury chmurowej -- wraz ze wzrostem bazy użytkowników rosną wydatki na moc obliczeniową, przestrzeń dyskową i przepustowość łącza. Koszty chmury obliczeniowej są bezpośrednio powiązane z poziomem aktywności użytkowników i stanowią główny składnik kosztów zmiennych w modelu SaaS.
- Koszty transakcyjne operatora płatności -- prowizje pobierane przez operatora płatności od każdej transakcji subskrypcyjnej, typowo wynoszące od 1,4% do 2,9% wartości transakcji plus stała opłata za transakcję.
- Koszty wysyłki wiadomości e-mail -- koszty usługi mailowej rosną proporcjonalnie do liczby użytkowników i częstotliwości wysyłanych powiadomień automatycznych.
- Koszty wsparcia technicznego -- przy wzroście bazy użytkowników rośnie wolumen zgłoszeń wymagających obsługi, co może generować potrzebę zwiększenia zasobów ludzkich dedykowanych wsparciu.

#pagebreak(weak: true)

Poniższa tabela podsumowuje strukturę kosztów QRLawyer według kategorii i charakteru:

#bmc-costs-table

Kluczową zaletą modelu SaaS z perspektywy struktury kosztów jest to, że koszty zmienne rosną wolniej niż przychody przy odpowiedniej skali -- co oznacza, że każdy kolejny użytkownik generuje coraz wyższą marżę. 
Osiągnięcie tego efektu wymaga jednak wcześniejszego poniesienia znaczących kosztów stałych związanych z wytworzeniem i utrzymaniem produktu, co czyni odpowiednie finansowanie początkowe warunkiem koniecznym powodzenia komercjalizacji.
